export const Colors = {
  light: {
    background: '#ffffff',
    surface: '#f8f8f8',
    surfaceSecondary: '#f0f0f0',
    selectedBg: '#f5f5f5',
    textPrimary: '#000000',
    textSecondary: '#666666',
    textTertiary: '#999999',
    border: '#dddddd',
    borderLight: '#eeeeee',
    primaryButtonBg: '#000000',
    primaryButtonText: '#ffffff',
    destructiveBg: '#fee2e2',
    destructiveText: '#dc2626',
    destructiveLink: '#cc0000',
    linkText: '#0066cc',
    calendarSelected: '#000000',
    calendarSelectedText: '#ffffff',
    calendarTodayText: '#000000',
  },
  dark: {
    background: '#000000',
    surface: '#1c1c1e',
    surfaceSecondary: '#2c2c2e',
    selectedBg: '#3a3a3c',
    textPrimary: '#ffffff',
    textSecondary: '#aeaeb2',
    textTertiary: '#636366',
    border: '#3a3a3c',
    borderLight: '#2c2c2e',
    primaryButtonBg: '#ffffff',
    primaryButtonText: '#000000',
    destructiveBg: '#3d1a1a',
    destructiveText: '#ff453a',
    destructiveLink: '#ff6b6b',
    linkText: '#0a84ff',
    calendarSelected: '#ffffff',
    calendarSelectedText: '#000000',
    calendarTodayText: '#ffffff',
  },
};
